Add link to Mega-Linter (including rstcheck)
myint/rstcheck pull request #73
Opened 2020-11-23 19:52 UTC by nvuillam

I added your nice tool in [Mega-Linter](https://nvuillam.github.io/mega-linter) :)

Please tell me if any information could be arranged on [rstcheck](https://nvuillam.github.io/mega-linter/descriptors/rst_rstcheck/) page :)

2022-04-15 21:58 UTC, Cielquan requested changes

2022-04-15 21:58 UTC, Cielquan commented on README.rst
> +Just install `Mega-Linter <https://nvuillam.github.io/mega-linter/>`__ in your repository, `rstcheck <https://nvuillam.github.io/mega-linter/descriptors/rst_rstcheck/>`__ is part of the 70 linters ac
Please add line breaks and a period like so:

```rst
Just install `Mega-Linter <https://nvuillam.github.io/mega-linter/>`__ in your repository,
`rstcheck <https://nvuillam.github.io/mega-linter/descriptors/rst_rstcheck/>`__
is part of the 70 linters activated out of the box.
```

2022-04-15 21:59 UTC, Cielquan commented
The docs over at MegaLinter are no longer up-to-date with the most recent releases:
https://megalinter.github.io/latest/descriptors/rst_rstcheck/#readme

2022-04-16 22:35 UTC, nvuillam commented
@Cielquan done :)

2022-04-17 08:00 UTC, Cielquan commented
LGTM

2022-04-17 08:00 UTC, Cielquan approved these changes

2022-04-17 09:09 UTC, Cielquan commented
Got a merge conflict because of my update of the README.

2022-04-17 09:15 UTC, merged

2022-04-17 09:15 UTC, Cielquan commented
Thanks for the contribution. :)

2022-04-17 15:02 UTC, nvuillam commented
Thanks for accepting the PR , have a nice day :)